name: Regenerate syntax highlighting function list

on:
  schedule:
    - cron: '0 0 * * 6'
  workflow_dispatch:

jobs:
  regenerate-funcs:
    name: Regenerate syntax highlighting function list
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Go v1.22
        uses: actions/setup-go@v3
        with:
          go-version: 1.22

      - name: Install Node v20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install lytfs
        run: go install github.com/jo3-l/yagfuncdata/cmd/lytfs@latest

      - name: Regenerate syntax highlighting function list
        run: node scripts/generate-syntax-highlighting-funcs.js

      - name: Generate token through GitHub app
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          author: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
          commit-message: 'chore(website): regenerate syntax highlighting function list'
          title: 'chore(website): regenerate syntax highlighting function list'
          body: |
            🤖 *beep boop*, this is an automated PR to regenerate the list of template functions used for syntax highlighting.
          branch: 'chore/regenerate-funcs'
          delete-branch: true
          assignees: jo3-l
          reviewers: jo3-l, l-zeuch
          token: ${{ steps.generate-token.outputs.token }}
